name: InstaWP WordPress Testing

on: push

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: nishantwebdev/wordpress-testing-automation@main
        with:
          INSTAWP_DOMAIN: stage.instawp.io
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_TEMPLATE_SLUG: testworkflow
          REPO_ID: 174
          INSTAWP_ACTION: create-site-template
